### ISSUE TITLE
Support for initial build

### ISSUE THREAD

**Issue by modeswitch** [js-platform/libwebrtc#1]
Moving discussion over from https://github.com/webrtcftw/goals/issues/1

**Comment by modeswitch** [comment]
The issue with boringssl is fixed now.

**Comment by szimek** [comment]
Thanks! It's better, but still fails for me:

```
$ npm install wrtc
-
> wrtc@0.0.44 install /Users/szimek/Projects/apps/test/node_modules/wrtc
> node-gyp rebuild

  ACTION Run build script /dev/null
TARGET_ARCH=x64 PLATFORM=darwin CONFIGURATION=Release PYTHON=python
: Preparing directories ...
: Cloning depot_tools ...
Cloning into 'depot_tools'...
POST git-upload-pack (189 bytes)
POST git-upload-pack (198 bytes)
remote: Sending approximately 13.99 MiB ...
remote: Counting objects: 807, done
remote: Finding sources: 100% (807/807)
remote: Total 807 (delta 75), reused 435 (delta 75)
Receiving objects: 100% (807/807), 2.74 MiB | 2.24 MiB/s, done.
Resolving deltas: 100% (75/75), done.
Checking connectivity... done.
: Cloning libwebrtc ...
Cloning into 'libwebrtc'...
POST git-upload-pack (205 bytes)
POST git-upload-pack (214 bytes)
remote: Counting objects: 11018, done.
remote: Compressing objects: 100% (8737/8737), done.
remote: Total 11018 (delta 1806), reused 9927 (delta 1644)
Receiving objects: 100% (11018/11018), 18.21 MiB | 4.38 MiB/s, done.
Resolving deltas: 100% (1806/1806), done.
Checking connectivity... done.
Checking out files: 100% (10144/10144), done.
: Updating clang ...
Trying to download prebuilt clang
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.6M  100 20.6M    0     0  5108k      0  0:00:04  0:00:04 --:--:-- 5108k
clang 218707 unpacked
: Generating build scripts ...
Updating projects from gyp files...
: Building libwebrtc ...
ninja: Entering directory `out/Release'
[630/630] LINK wrtc_build, POSTBUILDS
: Build complete

  TOUCH Release/obj.target/action_before_build.stamp
  CXX(target) Release/obj.target/wrtc/src/binding.o
  CXX(target) Release/obj.target/wrtc/src/create-offer-observer.o
  CXX(target) Release/obj.target/wrtc/src/create-answer-observer.o
  CXX(target) Release/obj.target/wrtc/src/set-local-description-observer.o
  CXX(target) Release/obj.target/wrtc/src/set-remote-description-observer.o
  CXX(target) Release/obj.target/wrtc/src/peerconnection.o
In file included from ../src/peerconnection.cc:17:
../src/peerconnection.h:181:38: warning: private field '_mediaConstraints' is not used [-Wunused-private-field]
  webrtc::MediaConstraintsInterface* _mediaConstraints;
                                     ^
1 warning generated.
  CXX(target) Release/obj.target/wrtc/src/datachannel.o
In file included from ../src/datachannel.cc:11:
../src/datachannel.h:116:24: warning: private field '_observer' is not used [-Wunused-private-field]
  DataChannelObserver* _observer;
                       ^
1 warning generated.
  SOLINK_MODULE(target) Release/wrtc.node
clang: error: no such file or directory: '../third_party/libwebrtc/out/Release/obj/talk/libjingle_peerconnection.a'
clang: error: no such file or directory: '../third_party/libwebrtc/out/Release/obj/talk/libjingle_p2p.a'
clang: error: no such file or directory: '../third_party/libwebrtc/out/Release/obj/talk/libjingle_media.a'
clang: error: no such file or directory: '../third_party/libwebrtc/out/Release/obj/webrtc/p2p/librtc_p2p.a'
clang: error: no such file or directory: '../third_party/libwebrtc/out/Release/obj/webrtc/base/librtc_base.a'
clang: error: no such file or directory: '../third_party/libwebrtc/out/Release/obj/webrtc/base/librtc_base_approved.a'
clang: error: no such file or directory: '../third_party/libwebrtc/out/Release/obj/chromium/src/net/third_party/nss/libcrssl.a'
clang: error: no such file or directory: '../third_party/libwebrtc/out/Release/obj/chromium/src/third_party/usrsctp/libusrsctplib.a'
make: *** [Release/wrtc.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/szimek/Projects/apps/test/node_modules/wrtc
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "wrtc"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.14
npm ERR! code ELIFECYCLE

npm ERR! wrtc@0.0.44 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wrtc@0.0.44 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the wrtc package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls wrtc
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/szimek/Projects/apps/test/npm-debug.log
```

**Comment by modeswitch** [comment]
Yeah, that's the same problem @TomKaltz is having. What happens when you do this from a cloned repo instead of from npm?

**Comment by modeswitch** [comment]
@szimek Feel free to jump onto #webrtc on irc.freenode.net to chat.

**Comment by modeswitch** [comment]
Ah, I see the problem. The paths are different on OSX for the static libraries. I'll push an updated `binding.gyp` but I'll need testers to see what libraries are missing.

**Comment by modeswitch** [comment]
This should be completely fixed now. Please open a new issue for any additional build problems on OSX.

Thanks to @szimek and @TomKaltz for their help with this!
